### ISSUE TITLE
Bug in vec2.h

### ISSUE THREAD

**Issue by ulfben** [TEAMarg/ID-34-Mystic-Balloon#26]
There's a typo on line 45 in vec2.h, in `operator -`

```
vec2 operator-(vec2 &lhs, const vec2 &rhs)
{
    //vec2 t = lhs;
    //t -= rhs;
    return (lhs += rhs); //Ooops!
}
```
`return (lhs += rhs);`  should be `return (lhs -= rhs);`

**Comment by JO3RI** [comment]
@Gaveno can you have a look at this comment ?

**Comment by JO3RI** [comment]
Issue has been solved already along other commits
